services:
  - type: web
    name: sherlock-tgbot
    runtime: python

    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn bot:app --host 0.0.0.0 --port $PORT

    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4

      - key: BOT_TOKEN
        sync: false

      - key: ADMIN_IDS
        sync: false

      - key: COOLDOWN
        value: "30"

      - key: MAX_RUNNING
        value: "2"

      - key: WEBHOOK_SECRET
        generateValue: true
